<!DOCTYPE html><html lang="en">	<head><title>Dajve Green</title><meta name='description' content="Web developer and system architect since the late 90s, with a focus on ecommerce and CRM. Currently heading up the technical team at allies.co.uk"><style type='text/css'>body {background:#39152E;color: #FFF;}code{font-family:'Ubuntu Mono',monospace;white-space: pre;}.cli-user{font-weight:700;color:#88DF34;}.cli-loc{font-weight:700;color:#709DCB;}a.noformat{text-decoration:none;color:inherit;}.md-h1{color:#F2D1D3;}.md-ln-label{color:#57B3D9;text-decoration:underline;}.md-ln-a{color:#9C6F8C;}.md-li-mark,.md-lineno{color:#F4E64F;}</style><link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700" rel="stylesheet"></head><body><code><span class='cli-user'>me@dajve</span>:<span class='cli-loc'>~</span>$ ls -l
total 32 
-rw-r----- 1 dajve www-data  286 May  3 08:53 ABOUT.md
-rw-r----- 1 dajve www-data   24 May  3 08:53 CONTACT.md
-rw-r----- 1 dajve www-data 1150 Sep  1 07:04 favicon.ico
-rw-r----- 1 dajve www-data 6102 May  3 08:55 index.html
-rw-r----- 1 dajve www-data  244 Sep 29 04:15 LINKS.md
-rw-r----- 1 dajve www-data 2510 May  3 08:54 O-HAI.txt
<span class='cli-user'>me@dajve</span>:<span class='cli-loc'>~</span>$ vi ABOUT.md 
<span class='md-lineno'> 1</span> <span class='md-h1'># Dajve Green</span>
<span class='md-lineno'> 2</span> 
<span class='md-lineno'> 3</span> Web developer and system architect since the late 90s, with a focus on 
   <a href="http://magento.com" class='noformat'>[<span class='md-ln-label'>ecommerce</span>](<span class='md-ln-a'>https://magento.com</span>)</a> since 2010 and <a href="https://www.orocrm.com" class='noformat'>[<span class='md-ln-label'>CRM</span>](<span class='md-ln-a'>https://www.orocrm.com</span>)</a> 
   since 2015.
<span class='md-lineno'> 4</span> Experienced in a wide range of front and backend technologies, platforms, and 
   methodologies.
<span class='md-lineno'> 5</span> Anatidaephile
<span class='cli-user'>me@dajve</span>:<span class='cli-loc'>~</span>$ vi CONTACT.md
<span class='md-lineno'> 1</span> <span class='md-li-mark'>-</span> Email: me@dajve.co.uk
<span class='cli-user'>me@dajve</span>:<span class='cli-loc'>~</span>$ vi LINKS.md
<span class='md-lineno'> 1</span> <span class='md-li-mark'>-</span> <a href="https://www.linkedin.com/in/dajve/" class='noformat'>[<span class='md-ln-label'>LinkedIn</span>](<span class='md-ln-a'>https://www.linkedin.com/in/dajve/</span>)</a>
<span class='md-lineno'> 2</span> <span class='md-li-mark'>-</span> <a href="https://github.com/dajve" class='noformat'>[<span class='md-ln-label'>GitHub</span>](<span class='md-ln-a'>https://github.com/dajve</span>)</a>
<span class='md-lineno'> 3</span> <span class='md-li-mark'>-</span> <a href="https://commercehero.io/dajve" class='noformat'>[<span class='md-ln-label'>Commerce Hero</span>](<span class='md-ln-a'>https://commercehero.io/dajve</span>)</a>
<span class='md-lineno'> 4</span> <span class='md-li-mark'>-</span> <a href="https://twitter.com/dajve" class='noformat'>[<span class='md-ln-label'>Twitter</span>](<span class='md-ln-a'>https://twitter.com/dajve</span>)</a>
<span class='md-lineno'> 5</span> <span class='md-li-mark'>-</span> <a href="https://u.magento.com/certification/directory/dev/46558/" class='noformat'>[<span class='md-ln-label'>Magento</span>](<span class='md-ln-a'>https://u.magento.com/certification/directory/dev/46558/</span>)</a>
<span class='cli-user'>me@dajve</span>:<span class='cli-loc'>~</span>$ cat O-HAI.txt
@@@@@@@@%###(&@@@@@@%/#*..#....        .....   .   .....,..,,     ...,,,,****,,
@@@@@@@@%###(&@@@@@@%/#*..#.....       .. ..      .....    ...,,,,,,,,*,,******
@@@@@@@@####(@@@@@@@&/#*..#,....                      ..,,,,,,,,,,,,,**,,,*****
@@@@@@@@####(@@@@@@@@((*..#,...,./. ..            ....,,,,,,,,,,,*,,,,*.,,*****
@@@@@@@@#####@@@@@@@@((*..%*...../,/**,,, ..  . ......,,,,*,,,*,,*,,,**,,,*****
@@@@@@@@###(#@@@@@@@@#(,..(/...,%##(((//****/,...,,...,,,***,,*,,**,*****,*****
@@@@@@@@###(#@@@@@@@@&(,...(*&%#(////*,,,,......, ,...,,,****,*,*********,*****
@&&&&@%@###(#@@@@@@@@@(,..&&%%(///**,,,............  .,,,***,,****,,****,,,....
@@@@@@&(###(%@@@@@@@@&/,,@@%#(((//**,,,,,............   ,****,,,,,........ ....
@@@@@@#@###(%@@@@@@@@%/,@@@%(((##/,,,.................    .,...................
@@@@@@%##(%@@@@@@@@%/@@@%(#,((*,,....................    ................ ...
@@@@@@&%###(&@@@@@@@@#/@&%#((,/*,.,...................     .............. .. .
@@@@@@@####(&@@@@@@@@#@&&(/,/,.,.... .......... ......     ............ .  .
@@@@@@@####(&@@@@@@@@////*,.,,..................    ..      ...... .. ..
@@@@@@@####(&@@@@%@@@%#/,...,#*......    ....,......        .....
@@@@@@@####/&@@@@(&(@@#/.,,*,#,.......................      . .
@@@@@@@####(&@@@@@@@@%%(/,,,&(,...............................
@@@@@&@####(&@@@@@(@@%@@&*(%#*,............................. .
@@@@@%@###((@@@@@@@@@&//#@#,................................
@@@@@#@###((@@@@@@@@&(/#&%/,.......................... ....
@@@@@(@###(#@@@@@@@@#/%##&(,,,...............................
@@@@@//###(#@@@@@@@@#/&%#((*,,..............................
@@@@/*%((#(%@@@@@@@@#/%&%%#(/,..   ..................... ..
%#@@#/#/%#(%@@@@@@@@(//&%%((*.,,........................
/@@@/###/,(*@@@@@@@@(/,&%##//,..........................
&&@@@%%%#/(%(@@@@@@@(/,,*#/*...   ...................
@(#&@&%%&((&@@@@@@@@(/,(#/##/,,...................... .
((%&*/,#(&@@@@@@@&(/,.(((/(/,.......................
&%%%##/*##(&@@@@@@@@(/,..#(##/,,........................
&&&&&/*###(&@@@@@@@@(*,.,*%#/,,........... ...........
%@#//(****/(@@#//((((#%(#*#(*,,.....  . ..............
/(*,.,..(*%*#.*/#*//(/#(##,,/***.......................
#(//**#,,(#..,//(((//##(#,,**&&%###(**,,,.............
@@&(%*..#(. ,**/////##((#*//%&&(((//*,,,,........
@@//,..#.  .**//((/#%((%(*/#%&&%#(/(/*/(/*,......
%(,,..*.  .**//(/##%(#(##,*#%%###(((#%%#/,.....
/,...,   .**/(#(##%((#(/(*,/((((((#%%%#(*.....   .
,.....  ,*//(((((#/#/((///***/(((#%##((((/*,,,
.,*....,///(((((((/#/(/**//*,*((#########(                                      </code></body></html>
